/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.view;

import main.controllers.ClientController;
import main.model.entities.Client;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author pablo
 */
public class FrmAddClient extends javax.swing.JPanel {

    /**
     * Creates new form FrmAddClient
     */
    private final ClientController clientController;
    private final FrmClient parent;

    public FrmAddClient(FrmClient parent) {
        initComponents();
        this.parent = parent;

        clientController = new ClientController();

        formBody.getVerticalScrollBar().setUnitIncrement(15);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formHeader = new javax.swing.JPanel();
        formTitle = new javax.swing.JLabel();
        formBody = new javax.swing.JScrollPane();
        formBodyContent = new javax.swing.JPanel();
        titleForm = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblDocument = new javax.swing.JLabel();
        txtDocument = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        formHeader.setBackground(new java.awt.Color(255, 255, 255));
        formHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        formHeader.setLayout(null);

        formTitle.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        formTitle.setText("Create client");
        formHeader.add(formTitle);
        formTitle.setBounds(10, 5, 460, 17);

        formBody.setBackground(new java.awt.Color(255, 255, 255));
        formBody.setBorder(null);
        formBody.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        formBodyContent.setBackground(new java.awt.Color(255, 255, 255));

        titleForm.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        titleForm.setText("Client creation form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblDocument.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblDocument.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDocument.setText("Document:");
        lblDocument.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtDocument.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtDocument.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtDocument.setOpaque(false);

        lblName.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName.setText("Name:");

        txtName.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtName.setOpaque(false);

        lblPhone.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPhone.setText("Phone:");

        txtPhone.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        lblEmail.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmail.setText("Email:");

        txtEmail.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        btnCreate.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnCreate.setText("Create client");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formBodyContentLayout = new javax.swing.GroupLayout(formBodyContent);
        formBodyContent.setLayout(formBodyContentLayout);
        formBodyContentLayout.setHorizontalGroup(
            formBodyContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBodyContentLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(formBodyContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formBodyContentLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(formBodyContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail)
                            .addComponent(lblPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDocument)
                            .addComponent(lblDocument, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtName)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone)
                            .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(formBodyContentLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(titleForm, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        formBodyContentLayout.setVerticalGroup(
            formBodyContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBodyContentLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(formBodyContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleForm, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lblDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        formBody.setViewportView(formBodyContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formBody)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(formBody, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:

        final JButton btnCancel = new JButton("Cancel");

        btnCancel.setBackground(new Color(108, 117, 125, 255));
        btnCancel.setForeground(Color.WHITE);
        btnCancel.setBorder(null);
        btnCancel.setFont(new Font("Poppins", 1, 11));
        btnCancel.setFocusPainted(false);
        btnCancel.setPreferredSize(new Dimension(100, 25));

        btnCancel.addActionListener((ActionEvent e) -> {
            JOptionPane.getRootFrame().dispose();
        });

        final JButton btnSave = new JButton("Save");

        btnSave.setBackground(new Color(71, 201, 162, 255));
        btnSave.setForeground(Color.WHITE);
        btnSave.setBorder(null);
        btnSave.setFont(new Font("Poppins", 1, 11));
        btnSave.setFocusPainted(false);
        btnSave.setPreferredSize(new Dimension(100, 25));

        btnSave.addActionListener((ActionEvent actionEvent) -> {

            JOptionPane.getRootFrame().dispose();

            final Client client = new Client(txtDocument.getText(), txtName.getText(), txtPhone.getText(), txtEmail.getText());

            try {
                clientController.createClient(client);
            } catch (Exception ex) {

            }

            JOptionPane.getRootFrame().dispose();

            final JButton btnSuccess = new JButton("Ok");

            btnSuccess.setBackground(new Color(71, 201, 162, 255));
            btnSuccess.setForeground(Color.WHITE);
            btnSuccess.setBorder(null);
            btnSuccess.setFont(new Font("Poppins", 1, 11));
            btnSuccess.setFocusPainted(false);
            btnSuccess.setPreferredSize(new Dimension(100, 25));

            btnSuccess.addActionListener((ActionEvent e) -> {
                parent.generateTable();
                JOptionPane.getRootFrame().dispose();
                cleanInputs();
                parent.parent.closeModalDialog();
            });

            final JButton[] btnSucessOption = {btnSuccess};

            JOptionPane.showOptionDialog(null, "<html><div align='center'>Success</div></html>\nThe records have been saved successfully.", "Successful Dialog", 0, JOptionPane.INFORMATION_MESSAGE, null, btnSucessOption, null);

        });

        final JButton[] btnOptions = {btnCancel, btnSave};

        JOptionPane.showOptionDialog(null, "Are you sure?\nDo you really want to keep these records? This process can be undone later.", "Confirm Dialog", 0, JOptionPane.WARNING_MESSAGE, null, btnOptions, null);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void cleanInputs() {
        txtDocument.setText("");
        txtName.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JScrollPane formBody;
    private javax.swing.JPanel formBodyContent;
    private javax.swing.JPanel formHeader;
    private javax.swing.JLabel formTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDocument;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel titleForm;
    private javax.swing.JTextField txtDocument;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
