/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.view;

import main.controllers.ArticleController;
import main.controllers.ClientController;
import main.model.entities.Article;
import main.model.entities.Client;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author pablo
 */
public final class FrmArticle extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmClient
     */
    public final Navigator parent;
    private final ArticleController articleController;

    public FrmArticle(Navigator parent) {
        initComponents();
        this.parent = parent;
        articleController = new ArticleController();
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        generateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        formTitle = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        body = new javax.swing.JPanel();
        btnAddArticle = new javax.swing.JButton();
        scrollTableArticles = new javax.swing.JScrollPane();
        tableArticles = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int vColIndex) {
                if(rowIndex != 5 && vColIndex != 5 && rowIndex != 6 && vColIndex != 6){
                    return false;
                }
                return true;
            }
        };
        txtSearch = new javax.swing.JTextField();
        lblQuery = new javax.swing.JLabel();

        setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        header.setLayout(null);

        formTitle.setFont(new java.awt.Font("Poppins", 1, 11)); // NOI18N
        formTitle.setText("Articles");
        header.add(formTitle);
        formTitle.setBounds(10, 0, 430, 25);

        btnClose.setText("<html>&times;</html>");
        btnClose.setFocusPainted(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        header.add(btnClose);
        btnClose.setBounds(480, 0, 70, 22);

        body.setBackground(new java.awt.Color(255, 255, 255));

        btnAddArticle.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        btnAddArticle.setText("Add Article");
        btnAddArticle.setFocusPainted(false);
        btnAddArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddArticleActionPerformed(evt);
            }
        });

        scrollTableArticles.setBackground(new java.awt.Color(255, 255, 255));
        scrollTableArticles.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tableArticles.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        tableArticles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableArticles.setGridColor(new java.awt.Color(204, 204, 204));
        tableArticles.setRowHeight(25);
        tableArticles.setShowGrid(true);
        scrollTableArticles.setViewportView(tableArticles);

        txtSearch.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        lblQuery.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        lblQuery.setForeground(new java.awt.Color(153, 153, 153));
        lblQuery.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddArticle)
                    .addComponent(scrollTableArticles, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addComponent(txtSearch)
                    .addComponent(lblQuery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnAddArticle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(scrollTableArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddArticleActionPerformed
        // TODO add your handling code here:
        FrmAddArticle frmAddArticle = new FrmAddArticle(this);
        this.parent.openModalDialog(frmAddArticle, 480, 425, 120, 40);
    }//GEN-LAST:event_btnAddArticleActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        this.parent.removeExternalContent();
        super.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        final String searchData = txtSearch.getText();
        if (txtSearch.getText().isEmpty()) {
            try {
                Thread.sleep(15);
                generateTable();
            } catch (InterruptedException interruptedException) {
            }
        }

        generateTableBySearch(searchData);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void generateTableBySearch(String name) {
        List<Article> articles = articleController.findArticlesByName(name);

        tableArticles.getTableHeader().setReorderingAllowed(false);
        tableArticles.getTableHeader().setResizingAllowed(false);

        tableArticles.setModel(articleController.listArticles(articles));

        lblQuery.setText("");
        lblQuery.setText("Se encontraron " + tableArticles.getRowCount() + " resultados");

        tableArticles.getColumnModel().getColumn(5).setCellRenderer(new ButtonRenderer());
        tableArticles.getColumnModel().getColumn(5).setCellEditor(new ButtonEditor(new JTextField()));

        tableArticles.getColumnModel().getColumn(6).setCellRenderer(new ButtonRenderer());
        tableArticles.getColumnModel().getColumn(6).setCellEditor(new ButtonEditor(new JTextField()));

        tableArticles.getTableHeader().setFont(new Font("Poppins", 0, 11));

        scrollTableArticles.setBackground(Color.white);
    }

    public void generateTable() {

        txtSearch.setText("");

        tableArticles.getTableHeader().setReorderingAllowed(false);
        tableArticles.getTableHeader().setResizingAllowed(false);

        tableArticles.setModel(articleController.listArticles());

        lblQuery.setText("");
        lblQuery.setText("Se encontraron " + tableArticles.getRowCount() + " resultados");

        tableArticles.getColumnModel().getColumn(5).setCellRenderer(new ButtonRenderer());
        tableArticles.getColumnModel().getColumn(5).setCellEditor(new ButtonEditor(new JTextField()));

        tableArticles.getColumnModel().getColumn(6).setCellRenderer(new ButtonRenderer());
        tableArticles.getColumnModel().getColumn(6).setCellEditor(new ButtonEditor(new JTextField()));

        tableArticles.getTableHeader().setFont(new Font("Poppins", 0, 11));

        scrollTableArticles.setBackground(Color.white);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btnAddArticle;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel formTitle;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQuery;
    private javax.swing.JScrollPane scrollTableArticles;
    private javax.swing.JTable tableArticles;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

//BUTTON RENDERER CLASS
    class ButtonRenderer extends JButton implements TableCellRenderer {

        //CONSTRUCTOR
        public ButtonRenderer() {
            //SET BUTTON PROPERTIES
            setOpaque(true);
            setFont(new Font("Poppins", 0, 11));
            setFocusPainted(false);
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object obj,
                boolean selected, boolean focused, int row, int col) {

            //SET PASSED OBJECT AS BUTTON TEXT
            setText((obj == null) ? "" : obj.toString());

            return this;
        }
    }

//BUTTON EDITOR CLASS
    class ButtonEditor extends DefaultCellEditor {

        protected JButton btn;
        private String lbl;
        private Boolean clicked;
        private int dataRowSelected;

        public ButtonEditor(JTextField txt) {
            super(txt);

            btn = new JButton();

            btn.setOpaque(true);
            btn.setFont(new Font("Poppins", 0, 11));
            btn.setFocusPainted(false);

            //WHEN BUTTON IS CLICKED
            btn.addActionListener((ActionEvent e) -> {
                fireEditingStopped();
                generateTable();
            });
        }

        //OVERRIDE A COUPLE OF METHODS
        @Override
        public Component getTableCellEditorComponent(JTable table, Object obj,
                boolean selected, int row, int col) {

            //SET TEXT TO BUTTON,SET CLICKED TO TRUE,THEN RETURN THE BTN OBJECT
            lbl = (obj == null) ? "" : obj.toString();
            btn.setText(lbl);
            dataRowSelected = Integer.parseInt(table.getValueAt(row, 0).toString()); //Code
            clicked = true;
            return btn;
        }

        //IF BUTTON CELL VALUE CHNAGES,IF CLICKED THAT IS
        @Override
        public Object getCellEditorValue() {

            if (clicked) {
                //SHOW US SOME MESSAGE

                final ClientController clientController = new ClientController();

                final JButton btnCancel = new JButton("Cancel");

                btnCancel.setBackground(new Color(108, 117, 125, 255));
                btnCancel.setForeground(Color.WHITE);
                btnCancel.setBorder(null);
                btnCancel.setFont(new Font("Poppins", 1, 11));
                btnCancel.setFocusPainted(false);
                btnCancel.setPreferredSize(new Dimension(100, 25));

                btnCancel.addActionListener((ActionEvent e) -> {
                    JOptionPane.getRootFrame().dispose();
                });

                final JButton btnSuccess = new JButton("Ok");

                btnSuccess.setBackground(new Color(71, 201, 162, 255));
                btnSuccess.setForeground(Color.WHITE);
                btnSuccess.setBorder(null);
                btnSuccess.setFont(new Font("Poppins", 1, 11));
                btnSuccess.setFocusPainted(false);
                btnSuccess.setPreferredSize(new Dimension(100, 25));

                btnSuccess.addActionListener((ActionEvent e) -> {
                    JOptionPane.getRootFrame().dispose();
                });

                final JButton[] btnSucessOption = {btnSuccess};

                if (lbl.equalsIgnoreCase("edit")) {
                    FrmEditArticle frmEditArticle = new FrmEditArticle(dataRowSelected, FrmArticle.this);

                    parent.openModalDialog(frmEditArticle, 480, 425, 120, 40);
                } else {

                    final JButton btnDelete = new JButton("Delete");

                    btnDelete.setBackground(new Color(220, 53, 69, 255));
                    btnDelete.setForeground(Color.WHITE);
                    btnDelete.setBorder(null);
                    btnDelete.setFont(new Font("Poppins", 1, 11));
                    btnDelete.setFocusPainted(false);
                    btnDelete.setPreferredSize(new Dimension(100, 25));

                    btnDelete.addActionListener((ActionEvent actionEvent) -> {
                        articleController.deleteArticle(dataRowSelected);

                        JOptionPane.getRootFrame().dispose();

                        JOptionPane.showOptionDialog(null, "<html><div align='center'>Success</div></html>\nThe records have been successfully removed.", "Successful Dialog", 0, JOptionPane.INFORMATION_MESSAGE, null, btnSucessOption, null);
                    });

                    final JButton[] btnOptions = {btnCancel, btnDelete};

                    JOptionPane.showOptionDialog(null, "Are you sure?\nDo you really want to delete these records? This process cannot be undone.", "Confirm Dialog", 0, JOptionPane.ERROR_MESSAGE, null, btnOptions, null);

                }
            }
            //SET IT TO FALSE NOW THAT ITS CLICKED
            clicked = false;
            return lbl;
        }

        @Override
        public boolean stopCellEditing() {

            //SET CLICKED TO FALSE FIRST
            clicked = false;
            return super.stopCellEditing();
        }

        @Override
        protected void fireEditingStopped() {
            // TODO Auto-generated method stub
            super.fireEditingStopped();
        }
    }

}
