/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.view;

import main.controllers.ClientController;
import main.model.entities.Client;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author pablo
 */
public class FrmEditClient extends javax.swing.JPanel {

    /**
     * Creates new form FrmAddClient
     */
    private final ClientController clientController;

    private final String document;

    private final FrmClient parent;

    public FrmEditClient(String document, FrmClient parent) {
        initComponents();

        this.document = document;
        this.parent = parent;

        clientController = new ClientController();

        txtDocument.setEnabled(false);
        
        formBody.getVerticalScrollBar().setUnitIncrement(15);
        
        uploadInformation(document);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formHeader = new javax.swing.JPanel();
        formTitle = new javax.swing.JLabel();
        formBody = new javax.swing.JScrollPane();
        formBodyContent = new javax.swing.JPanel();
        titleForm = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtDocument = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        formHeader.setBackground(new java.awt.Color(255, 255, 255));
        formHeader.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        formHeader.setLayout(null);

        formTitle.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        formTitle.setText("Edit client");
        formHeader.add(formTitle);
        formTitle.setBounds(10, 5, 460, 17);

        formBody.setBackground(new java.awt.Color(255, 255, 255));
        formBody.setBorder(null);
        formBody.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        formBodyContent.setBackground(new java.awt.Color(255, 255, 255));

        titleForm.setFont(new java.awt.Font("Poppins", 0, 13)); // NOI18N
        titleForm.setText("Client information edit form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Document:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtDocument.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtDocument.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtDocument.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Name:");

        txtName.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtName.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Phone:");

        txtPhone.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Email:");

        txtEmail.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));

        btnUpdate.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        btnUpdate.setText("Update information");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formBodyContentLayout = new javax.swing.GroupLayout(formBodyContent);
        formBodyContent.setLayout(formBodyContentLayout);
        formBodyContentLayout.setHorizontalGroup(
            formBodyContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBodyContentLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(formBodyContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formBodyContentLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(formBodyContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(txtDocument, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(formBodyContentLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(titleForm, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        formBodyContentLayout.setVerticalGroup(
            formBodyContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formBodyContentLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(formBodyContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleForm, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        formBody.setViewportView(formBodyContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formBody)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(formBody, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        final JButton btnCancel = new JButton("Cancel");

        btnCancel.setBackground(new Color(108, 117, 125, 255));
        btnCancel.setForeground(Color.WHITE);
        btnCancel.setBorder(null);
        btnCancel.setFont(new Font("Poppins", 1, 11));
        btnCancel.setFocusPainted(false);
        btnCancel.setPreferredSize(new Dimension(100, 25));

        btnCancel.addActionListener((ActionEvent e) -> {
            JOptionPane.getRootFrame().dispose();
        });

        final JButton btnEdit = new JButton("Edit");

        btnEdit.setBackground(new Color(238, 183, 17, 255));
        btnEdit.setForeground(Color.WHITE);
        btnEdit.setBorder(null);
        btnEdit.setFont(new Font("Poppins", 1, 11));
        btnEdit.setFocusPainted(false);
        btnEdit.setPreferredSize(new Dimension(100, 25));

        btnEdit.addActionListener((ActionEvent actionEvent) -> {

            JOptionPane.getRootFrame().dispose();

            clientController.editClient(document,
                    new Client(
                            this.txtName.getText(),
                            this.txtPhone.getText(),
                            this.txtEmail.getText()));

            JOptionPane.getRootFrame().dispose();

            final JButton btnSuccess = new JButton("Ok");

            btnSuccess.setBackground(new Color(71, 201, 162, 255));
            btnSuccess.setForeground(Color.WHITE);
            btnSuccess.setBorder(null);
            btnSuccess.setFont(new Font("Poppins", 1, 11));
            btnSuccess.setFocusPainted(false);
            btnSuccess.setPreferredSize(new Dimension(100, 25));

            btnSuccess.addActionListener((ActionEvent e) -> {
                parent.generateTable();
                JOptionPane.getRootFrame().dispose();
                parent.parent.closeModalDialog();
            });

            final JButton[] btnSucessOption = {btnSuccess};

            JOptionPane.showOptionDialog(null, "<html><div align='center'>Success</div></html>\nThe records have been successfully updated.", "Successful Dialog", 0, JOptionPane.INFORMATION_MESSAGE, null, btnSucessOption, null);

        });

        final JButton[] btnOptions = {btnCancel, btnEdit};

        JOptionPane.showOptionDialog(null, "Are you sure?\nDo you really want to edit these records? This process cannot be undone.", "Confirm Dialog", 0, JOptionPane.WARNING_MESSAGE, null, btnOptions, null);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void uploadInformation(String document) {
        Client client = clientController.findClientByDocument(document);
        txtDocument.setText(document);
        txtName.setText(client.getName());
        txtPhone.setText(client.getPhone());
        txtEmail.setText(client.getEmail());

        formTitle.setText(formTitle.getText() + " - " + client.getName());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane formBody;
    private javax.swing.JPanel formBodyContent;
    private javax.swing.JPanel formHeader;
    private javax.swing.JLabel formTitle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titleForm;
    private javax.swing.JTextField txtDocument;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
